### ISSUE TITLE
Import UNRST Error - bad dates?

### ISSUE THREAD

**Issue by trhallam** [equinor/ecl#639] opened 2019-07-12 05:49 UTC
I'm running into some issues loading a opm-flow output UNRST file.

The report dates run from 2020 to 2060ish and at 2038 an `OSError [Errno 22] Invalid Argument`.

A bit more digging and it appears the `CTime` class is being passed a negative integer. The Sequences appear to be present in the file if I use `.iget_kw('SEQNUM')` but for whatever reason the dates are mangled and `'iget_restart_sim_time` for values after 2038 throws the error.

Should note that the opm-flow output was created on linux but I am looking at the files on Win10 with libecl 2.4.

Cheers
Tony

**Comment by joakim-hove** [comment] 2019-07-12 06:04
Hello;

this sounds very much like a [2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem) - so I guess the problem is with the `UNRST` files generated by opm/flow. These file were originally created using libecl, but as of quite recently they are created with code internal in opm/flow. Have you compiled flow yourself, or are you using a binary package for flow?

**Comment by trhallam** [comment] 2019-07-12 06:59
Yeah, I was thinking about shifting the years as a quick fix.

The UNRST looks ok when I do the method mentioned above. It was created using a self compiled 2019.4-pre version of flow. I can update my version of libecl on windows relatively easily if that is the problem.

**Comment by trhallam** [comment] 2019-07-12 07:08
Not sure if it's helpful but here is the traceback when I call EclFile._i_get_restart_time(40), this is after 2038.

```
<ecl.util.util.ctime.CTime object at 0x000001FE2B979828>
DATA_TYPE:<class 'ctypes.c_long'>
LEGAL_TYPES:[<class 'ctypes.c_byte'>, <class 'ctypes.c_ubyte'>, <class 'ctypes.c_short'>, <class 'ctypes.c_ushort'>, <class 'ctypes.c_long'>, <class 'ctypes.c_ulong'>, <class 'ctypes.c_long'>, <class 'ctypes.c_ulong'>, <class 'ctypes.c_bool'>, <class 'ctypes.c_char'>, <class 'ctypes.c_float'>, <class 'ctypes.c_double'>]
TYPE_NAME:'time_t'
stripped:'Traceback (most recent call last):\n  File "c:\\Users\\trhal\\.vscode\\extensions\\ms-python.python-2019.6.24221\\pythonFiles\\lib\\python\\ptvsd\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_resolver.py", line 214, in _get_py_dictionary\n    attr = getattr(var, name)\n  File "C:\\Users\\trhal\\Anaconda3\\envs\\etlp_conda_dev\\lib\\site-packages\\ecl\\util\\util\\ctime.py", line 141, in stripped\n    return time.strptime(self, "%Y-%m-%d %H:%M:S%")\n  File "C:\\Users\\trhal\\Anaconda3\\envs\\etlp_conda_dev\\lib\\_strptime.py", line 559, in _strptime_time\n    tt = _strptime(data_string, format)[0]\n  File "C:\\Users\\trhal\\Anaconda3\\envs\\etlp_conda_dev\\lib\\_strptime.py", line 329, in _strptime\n    raise TypeError(msg.format(index, type(arg)))\nTypeError: strptime() argument 0 must be str, not <class \'ecl.util.util.ctime.CTime\'>\n'
_BaseCValue__value:c_long(-1517898496)
```

**Comment by dotfloat** [comment] 2020-12-17 11:53
Closing due to the issue having already been resolved. Please reopen if this isn't the case.

**Closed** 2020-12-17 11:53 UTC

**Comment by tpradeep** [comment] 2021-03-18 15:43
I am having 2038 problem in Windows 10 while retrieving dates from Eclipse generated restart file.

`rst.iget_restart_sim_time(6661)`
`datetime.datetime(2038, 1, 1, 0, 0)`

`rst.iget_restart_sim_time(6662)`

> Traceback(most recent call last):
> 
>   File "<ipython-input-48-9e3a86d5c74f>", line 1, in <module>
>     rst.iget_restart_sim_time(6662)
> 
>   File "C:\Users\P.Tummala\Anaconda3\envs\pysim\lib\site-packages\ecl\eclfile\ecl_file.py", line 653, in iget_restart_sim_time
>     return ct.datetime()
> 
>   File "C:\Users\P.Tummala\Anaconda3\envs\pysim\lib\site-packages\ecl\util\util\ctime.py", line 59, in datetime
>     return datetime.datetime(*self.time()[0:6])
> 
>   File "C:\Users\P.Tummala\Anaconda3\envs\pysim\lib\site-packages\ecl\util\util\ctime.py", line 52, in time
>     return time.gmtime(self.value())
> 
> OSError: [Errno 22] Invalid argument

Any ideas on how to fix this?
